[server]
port = 5757
headless = true
address = "0.0.0.0"

[theme]
base = "dark"
primaryColor = "#00ff88"
backgroundColor = "#07070d"
secondaryBackgroundColor = "#111118"
textColor = "#d0d0e0"
font = "monospace"
